require_relative '../lib/amber'

# ======================================================================
# Advanced Amber Example: Auto-Analyzing a Git Repository (Optimized DSL)
# This example demonstrates:
# 1. Defining complex generic Tools (with varying Sandbox limits)
# 2. Defining generic Worker Agents
# 3. Using the `orchestrate` DSL macro to automatically spin up a Planner 
#    that uses `spawn_job` to dynamically build the entire execution pipeline!
# ======================================================================

# --- 1. Define Tools with Configurable Sandbox Arguments ---
class GitShellTool < Amber::Tool::Base
  name 'run_shell_in_git_repo'
  description 'Execute bash-like Ruby system commands to explore the repo (e.g. Dir.glob, File.read)'
  
  parameters(
    type: 'object',
    properties: {
      ruby_code: { type: 'string', description: 'Ruby code to evaluate, e.g., File.read("README.md")' }
    },
    required: ['ruby_code']
  )

  def execute(args)
    # Give the executor aggressive boundaries since we are just reading files
    executor = Amber::Sandbox::Executor.new(memory_limit_mb: 100, cpu_limit_sec: 5)
    
    begin
      result = executor.execute(args['ruby_code'])
      "Execution output: #{result}"
    rescue => e
      "Error: #{e.message}"
    end
  end
end

# Reindex the tool registry to pick up our custom script-level tool
Amber::ToolRegistry.reindex!

# --- 2. Build the Amber Engine ---
engine = Amber::Engine.build do
  
  # 1. State/Context Definition
  environment target_repo: '/Users/kael/workbench/ruby_lab/amber'

  # 2. Define our standard Worker pool
  # We don't even need to assign them to Jobs! The Engine will grab any Agent
  # that can handle the Dynamic Job if no specific agent is requested.
  agent :scout, 
        profile_name: 'glm',
        system_prompt: "You are a Git Repo Scout. You execute code to look at the repo's files.",
        tools: [:run_shell_in_git_repo]

  # 3. Trigger Auto-Orchestration!
  # This single line auto-generates a Planner Agent inside the Engine.
  # The Planner will read the goal, analyze it, and use its built-in `spawn_job` 
  # tool to generate N number of sub-jobs to read files, summarize, and report.
  # The Engine will natively intercept these new jobs and assign them to `:scout`.
  orchestrate "Analyze the git repo in the context (`target_repo`). Read the README and list the root files. Provide a final summary of what the project is to the context key `:final_summary`."
  
  # 4. We can still define explicit jobs that wait for the auto-planned sequence to finish!
  job :print_final_summary do
    depends_on { |ctx| ctx.get(:final_summary) != nil }
    action "Print the final summary generated by the auto-orchestrated jobs."
    executed_by do |ctx|
      puts "\n\n🎉 [FINAL OUTPUT] \n#{ctx.get(:final_summary)}"
    end
  end
  
end

if __FILE__ == $0
  puts "Running Auto-Orchestrating Git Repo Reader Example..."
  engine.run!
end
